---
# defaults file for create_standby

scripts_dir: ["{{ work_dir }}", "scripts"]
done_dir: ["{{ work_dir }}", "done"]

prenfsconfig:
 lpp_src:
    # !!! update !!!
 subdir: ''

ora_version: "19.3.0.0.0"
standby_cpu_core: 4
primary_cpu_core: 4
with_backup: false
dataguard_protection_mode: maximum_performance
