---
# defaults file for primary_config

scripts_dir: [ "{{ work_dir }}", "scripts" ]
done_dir: [ "{{ work_dir }}", "done" ]

prenfsconfig:
 lpp_src:
    # !!! update !!!
  subdir: ''

ora_version: "19.3.0.0.0"
db_port: 1521
dataguard_protection_mode: maximum_performance
