---
# defaults file for dataguard_precheck

scripts_dir: ["{{ work_dir }}", "scripts"]
done_dir: ["{{ work_dir }}", "done"]

prenfsconfig:
 lpp_src:
    # !!! update !!!
  subdir: ''

ora_version: "19.3.0.0.0"
ignore_precheck: false
