---
# defaults file for standby_config

scripts_dir: [ "{{ work_dir }}", "scripts" ]
done_dir: [ "{{ work_dir }}", "done" ]

prenfsconfig:
 lpp_src:
    # !!! update !!!
  subdir: ''

ora_version: "19.3.0.0.0"
with_backup: false
db_port: 1521